name: Test File
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Kind cluster
        uses: Sau1506mya/Test_action/kind@main
